### PR TITLE
Rh designer commentary

### PR DESCRIPTION
**Pull request by vesem**
Please let me know if you would like any changes.

### CODE REVIEW

**Comment by vesem** [comment]
Thanks, I'll get those changed.

**Comment by ilaunchbury** [comment]
@vesem, do you know when you'll be able to make the changes?

**Comment by vesem** [comment]
Sorry about that, I didn't get to it last weekend on my hobby time.   I can go ahead and close this out then resubmit once I get the changes ready.

**Comment by ilaunchbury** [comment]
Just leave it open, and any new commits will automatically get added. Give me a shout when you're done.

**Comment by vesem** [comment]
Should be ready now.  Sorry about letting this sit for a while.

**Pull request merged**
