### PR TITLE
Updated Codex: Blood Angels points from CA.

### PR DESCRIPTION
**Pull request by mihtjel**
Updated Codex: Blood Angels points from CA.

### CODE REVIEW

**Comment by mihtjel** [comment]
Why was this closed/not merged?

**Comment by tredzko** [comment]
@WindstormSCR Are there plans to add the CA2018 changes to blood angels since this was closed instead of merged?

**Comment by alphalas** [comment]
@mihtjel @tredzko Commits made to the files without first talking to the maintainer for said files on gitter is pretty much a guaranteed autoclose/no merge; not because of you not being the maintainer but because of how the merges get goofy when more then 1 person is working on the same file at the same time. PLEASE, talk to us on gitter BEFORE you go committing changes. Thank you!

**Comment by alphalas** [comment]
fc6e9324-78dc-4bd5-9c2d-e78ba5f9fbf3
For reference, it’s the first paragraph on the readme.

**Comment by tredzko** [comment]
@alphalas Thanks for the insight! I wasn't aware of the circumstances and I'm watching all of your awesome work for CA2018 with baited breath. I'm a BA player, so I saw this and was super curious.

**Comment by tredzko** [comment]
@alphalas Thanks for the insight! I wasn't aware of the circumstances and I'm watching all of your awesome work for CA2018 with baited breath. I'm a BA player, so I saw this and was super curious.

**Comment by mihtjel** [comment]
@alphalas Fair enough, I didn't read that as pertaining to pull requests. I'll leave you to it and submit issues instead of pull requests :-)

**Pull request closed without merging**
