### PR TITLE
Tau Empire - The Eight.One

### PR DESCRIPTION
**Pull request by GenWilhelm**
Revised The Eight for better view UX.

### CODE REVIEW

**Comment by amis92** [comment]
I'm not entirely convinced, as it's only helping for "inline" view. All the other aspects (selecting the entry, removing the entry, viewing in different layouts) don't improve or actually get worse.

Though, if the majority of reviewers approve, I'm fine with merging it.

**Comment by Kohato** [comment]
Do we have a quick screen of how it used to look?

**Comment by Kohato** [comment]
While I like the new output - I do not like it as a detachment on it's own now that I see it.

**Comment by alphalas** [comment]
Yeah no custom detachments are no bueno I’m afraid

**Pull request closed without merging**
