### PR TITLE
Drukhari - Faction Keyword Filter

### LINKED ISSUE #1203: Sub-Faction Selector for Druhkari?
File/Catalogue: Druhkari v.11

BattleScribe version: 2.01.

Platform: Windows

Dropbox: No

Description: Could a system similar to the CSM's, where you have the option to select a legion be added to the Druhkari? With options for Kabal, Wych Cult, and Haemonculus Coven, automatically restricting your units? I think this would help speed up army creation and I for one, as well as other Druhkari players, would greatly appreciate it. Thanks for all the great work!

### PR DESCRIPTION
**Pull request by GenWilhelm**
Added an optional filter to hide entries other than those with the selected faction keyword(s).
Closes #1203.

### CODE REVIEW

**Comment by FarseerVeraenthis** [comment]
is this really needed??

**Comment by GenWilhelm** [comment]
I happen to know people who want this feature, hence my particular interest in its implementation.

They way I've put it in makes it completely optional, so it won't affect people who don't want to use it, and doesn't change any entries, so it won't invalidate existing rosters.

**Comment by Toreador13** [comment]
I am looking at this, reviewing and thinking. I don't see any real obvious issues with this. 

The biggest thing I can see is that if some devices don't react well to it, or have any weird issues. Seeing if I see anything.

**Comment by FarseerVeraenthis** [comment]
My cavalier attitude says that if more than one person wants it and it won't have much impact on everyone else then just merge it.... But I'll leave the final merge up to you toreador13 :smile:

**Comment by Toreador13** [comment]
Yeah, I almost did that last night, but wanted to make sure there wasn't any oddness, after my PC did some odd things while looking at the list. I can't recreate, so it must have just been Battlescribe doing something funny. I was trying to see if maybe there was a cleaner or better way to do that. Kind of wish there was a way to filter categories, or hide/unhide by category tags. That would actually probably make a lot of game systems easier, to just tag for certain filters and go.

**Comment by Toreador13** [comment]
An interesting bug with this, is that once you choose units for your roster, you can no longer filter. So say I add an Archon,  Trueborn, and a Ravager, then select a filter for <Wych Cult> the Archon, Trueborn and Ravager do not hide. So it can't really be used to filter after you have chosen unit already that are outside the filter.

**Comment by alphalas** [comment]
Yeah that's a known BS behavior- it won't remove selections that are hidden, just throw errors that you can't have any, they're hidden.

**Comment by FarseerVeraenthis** [comment]
Funtabulous!

**Pull request merged**
