### PR TITLE
SPACE MARINES ERRATA - August 2019 - Space Wolves changes

### PR DESCRIPTION
**Pull request by Guy-Markman**
Changed everything that was changed in the August 2019 errata for the space wolves file only. Hasn't changed things in Space Marines File.

### CODE REVIEW

**Comment by Guy-Markman** [comment]
Changes from here:
https://www.warhammer-community.com/wp-
content/uploads/2019/08/warhammer_40000_space_marines_errata_en.pdf

**Comment by Guy-Markman** [comment]
Will add shock assault and send again

**Comment by CrusherJoe** [comment]
Guy this looks like quality work to me my man. I'm going to merge it and check it out. We can come back and add Shock Assault to this (or revert back if something terrible happens. 😄 )

**Comment by Guy-Markman** [comment]
Hi. I've added a new merge request to the other rules and new units

**Pull request merged**
